### ISSUE TITLE
Save game choice

### ISSUE THREAD

**Issue by joaopedrodcf** [joaopedrodcf/yokaidex#13]
Would be good to save in local storage the choice that the user made of the game, like this when it arrives in the app again we could not show the screen to choose the game and show I'm the list of Yokais from is game version.

**Comment by joaopedrodcf** [comment]
Also this is important because sometimes a use can refresh the page and if that happens it will see the information from the yokai watch 3 because is the default in the initial state of the app.

**Comment by log1NVolcom** [comment]
i can take care of that, sounds pretty important to me
