### ISSUE TITLE
Contact us page

### ISSUE THREAD

**Issue by joaopedrodcf** [joaopedrodcf/yokaidex#22]
Create a page where the users can send a message to us creators and like that we could find out if we have bugs in the app for example. This backend for this could be in node and also could be a separate project that would have an endpoint that we would call in the front end for do this functionality.
We could use nodemailer to do this !

**Comment by log1NVolcom** [comment]
I will work on this!

>Expect great things

**Comment by joaopedrodcf** [comment]
Nice 🤜🤛
