### ISSUE TITLE
Go back in the header

### ISSUE THREAD

**Issue by joaopedrodcf** [joaopedrodcf/yokaidex#47]
So while doing the PR #46  I created a go back in the header. 

It works but not as normally an application works with the go back.

Example: 

Click on the profile of a person A
Click on a profile B of a retweet from this person
Go back, it goes back to the profile of  A
Go back, it goes to the home screen of the app

React-router has the goBack() but to use it the go back should be a button that calls this function instead of being a link, we can try to go this way is easier. 

The other way I'm thinking create a state with an array of the locations that a person has done, and remove every time the user goes back.

**Comment by joaopedrodcf** [comment]
Today found a problem during some tests and maybe this becomes more priority, basically:

You go into a yokai then you choose one of its evolutions and you want to go back to home, but it instead of going to the correct version goes to do `/` that is also the yokai watch 3 version

**Comment by joaopedrodcf** [comment]
This also happens when you go into baffle board and click on a yokai and then want to go back

**Comment by log1NVolcom** [comment]
i take this
